return {
  -- 'folke/noice.nvim',
  -- event = 'VeryLazy',
  -- opts = {
  --   -- add any options here
  -- },
  -- dependencies = {
  --   -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
  --   'MunifTanjim/nui.nvim',
  --   -- OPTIONAL:
  --   --   `nvim-notify` is only needed, if you want to use the notification view.
  --   --   If not available, we use `mini` as the fallback
  --   -- 'rcarriga/nvim-notify',
  -- },
  -- config = function()
  --   require('noice').setup {
  --   -- cmdline = { enabled = true, view = 'cmdline', format { lua = false }, },
  --   lsp = {
  --   -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
  --       override = {
  --         ["vim.lsp.util.convert_input_to_markdown_lines"] = true,
  --         ["vim.lsp.util.stylize_markdown"] = true,
  --         ["cmp.entry.get_documentation"] = true, -- requires hrsh7th/nvim-cmp
  --       },
  --   },
  --     presets = {
  --       bottom_search = false, -- use a classic bottom cmdline for search
  --       command_palette = true, -- position the cmdline and popupmenu together
  --       long_message_to_split = false, -- long messages will be sent to a split
  --       inc_rename = true, -- enables an input dialog for inc-rename.nvim
  --       lsp_doc_border = true, -- add a border to hover docs and signature help
  --     },
  --     routes = {
  --       {
  --       -- don't show file written messages
  --         filter = {
  --           event = 'msg_show',
  --           kind = '',
  --           find = 'written',
  --         },
  --         opts = { skip = true },
  --       },
  --       {
  --       -- show recording macro messages
  --         view = 'notify',
  --         filter = { event = 'msg_showmode' },
  --       },
  --     },
  --   }
  --   -- require('notify').setup {
  --   --   render = 'default',
  --   --   stages = 'fade',
  --   --   merge_duplicates = true,
  --   --   timeout = 2000,
  --   --   on_open = function(win)
  --   --     vim.api.nvim_win_set_config(win, { focusable = false })
  --   --   end,
  --   -- }
  -- end,
}
